export const GET_ARTICLELIST = 'article/GET_ARTICLELIST'
export const SHOW_MSG = 'commom/SHOW_MSG'
export const HIDE_MSG = 'commom/HIDE_MSG'
export const LOGIN = 'commom/LOGIN'
export const LOGOUT = 'commom/LOGOUT'
export const SHOW_AJAX_LOADING = 'commom/SHOW_AJAX_LOADING'
export const HIDE_AJAX_LOADING = 'commom/HIDE_AJAX_LOADING'
export const SWITCH_OPEN_MODAL = 'commom/SWITCH_OPEN_MODAL'
export const GET_BROADCAST_LIST = 'broadcast/GET_BROADCAST_LIST'
export const GET_COURSE_LIST = 'course/GET_COURSE_LIST'
export const GET_DASHBOARD_LIST = 'dashboard/GET_DASHBOARD_LIST'
export const GET_NOTICE_LIST = 'notice/GET_NOTICE_LIST'
export const GET_ORGANIZATION_LIST = 'organization/GET_ORGANIZATION_LIST'
export const GET_SETTING_LIST = 'setting/GET_SETTING_LIST'
export const GET_STATISTICS_LIST = 'statistics/GET_STATISTICS_LIST'
export const GET_SYSTEM_LIST = 'system/GET_SYSTEM_LIST'
export const GET_TUTOR_LIST = 'tutor/GET_TUTOR_LIST'
export const GET_USER_LIST = 'user/GET_USER_LIST'
export const GET_WORK_BOOK_LIST = 'workBook/GET_WORK_BOOK_LIST'

// 工作圈模块
export const GET_WORK_ZONE_LISTS = 'workZone/GET_WORK_ZONE_LISTS'
export const GET_JOB_CIRCLE_ORGANIZATION_LISTS = 'workZone/GET_JOB_CIRCLE_ORGANIZATION_LISTS'
export const GET_JOB_CIRCLE_HIT_LISTS = 'workZone/GET_JOB_CIRCLE_HIT_LISTS'
export const GET_JOB_CIRCLE_MENBER_LISTS = 'workZone/GET_JOB_CIRCLE_MENBER_LISTS'
export const GET_JOB_CIRCLE_MENBER_DETAILS = 'workZone/GET_JOB_CIRCLE_MENBER_DETAILS'
