export const GET_ARTICLELIST = 'article/GET_ARTICLELIST'
export const SHOW_AJAX_LOADING = 'commom/SHOW_AJAX_LOADING'
export const HIDE_AJAX_LOADING = 'commom/HIDE_AJAX_LOADING'
export const SWITCH_OPEN_MODAL = 'commom/SWITCH_OPEN_MODAL'
export const GET_NOTICE_LIST = 'notice/GET_NOTICE_LIST'
export const GET_ORGANIZATION_LIST = 'organization/GET_ORGANIZATION_LIST'
export const GET_SETTING_LIST = 'setting/GET_SETTING_LIST'
export const GET_STATISTICS_LIST = 'statistics/GET_STATISTICS_LIST'
export const GET_SYSTEM_LIST = 'system/GET_SYSTEM_LIST'
export const GET_USER_LIST = 'user/GET_USER_LIST'
export const GET_WORK_BOOK_LIST = 'workBook/GET_WORK_BOOK_LIST'

// 工作圈模块
export const GET_WORK_ZONE_LISTS = 'workZone/GET_WORK_ZONE_LISTS'
export const GET_JOB_CIRCLE_ORGANIZATION_LISTS = 'workZone/GET_JOB_CIRCLE_ORGANIZATION_LISTS'
export const GET_JOB_CIRCLE_HIT_LISTS = 'workZone/GET_JOB_CIRCLE_HIT_LISTS'
export const GET_JOB_CIRCLE_MENBER_LISTS = 'workZone/GET_JOB_CIRCLE_MENBER_LISTS'
export const GET_GROUP_LISTS = 'workZone/GET_GROUP_LISTS'
export const UPDATE_GROUP_LISTS = 'workZone/UPDATE_GROUP_LISTS'
export const GET_MENBER_LISTS = 'workZone/GET_MENBER_LISTS'
export const GET_JOB_CIRCLE_MENBER_DETAILS = 'workZone/GET_JOB_CIRCLE_MENBER_DETAILS'
export const GET_JOB_CIRCLE_NOTE_LISTS = 'workZone/GET_JOB_CIRCLE_NOTE_LISTS'
export const GET_JOB_CIRCLE_COMMENT_FIRST_LISTS = 'workZone/GET_JOB_CIRCLE_COMMENT_FIRST_LISTS'
export const GET_JOB_CIRCLE_COMMENT_SECOND_LISTS = 'workZone/GET_JOB_CIRCLE_COMMENT_SECOND_LISTS'
export const GET_JOB_CIRCLE_TOP_NUM = 'workZone/GET_JOB_CIRCLE_TOP_NUM'

//公共宫模块接口
export const SHOW_MSG = 'commom/SHOW_MSG'
export const HIDE_MSG = 'commom/HIDE_MSG'
export const LOGIN = 'commom/LOGIN'
export const LOGOUT = 'commom/LOGOUT'
export const GET_UPLOAD_CONFIG = 'commom/GET_UPLOAD_CONFIG'

// 导师模块
export const GET_TUTOR_LIST = 'tutor/GET_TUTOR_LIST'
export const GET_TUTOR_OUTER_LIST = 'tutor/GET_TUTOR_OUTER_LIST'


// 直播模块
export const GET_CATEGORY_LIST = 'broadcast/GET_CATEGORY_LIST'
export const UPDATE_CATEGORY_LIST = 'broadcast/UPDATE_CATEGORY_LIST'
export const GET_LIVE_REVIEW_LIST = 'broadcast/GET_LIVE_REVIEW_LIST'
export const GET_LIVE_DETAILS = 'broadcast/GET_LIVE_DETAILS'
export const GET_LIVE_MENBER_LIST = 'broadcast/GET_LIVE_MENBER_LIST'
export const GET_LIVE_INVISIBLE_LIST = 'broadcast/GET_LIVE_INVISIBLE_LIST'
export const GET_LIVE_LIST = 'broadcast/GET_LIVE_LIST'
export const GET_LIVE_PROBLEM_LIST = 'broadcast/GET_LIVE_PROBLEM_LIST'


// 课程模块
export const GET_COURSE_LISTS = 'course/GET_COURSE_LISTS'
export const GET_COURSE_DEATAILS = 'course/GET_COURSE_DEATAILS'
export const GET_COURSE_PEAPLE = 'course/GET_COURSE_PEAPLE'
export const GET_COURSE_PEAPLE_HITS = 'course/GET_COURSE_PEAPLE_HITS'
export const GET_COURSE_ORGANAZATIOMNS = 'course/GET_COURSE_ORGANAZATIOMNS'
export const GET_COURSE_CATAGORY = 'course/GET_COURSE_CATAGORY'

// 工作台模块
export const GET_COMPANY_INFOS = 'common/GET_COMPANY_INFOS'
export const GET_USERS_LISTS = 'dashboard/GET_USERS_LISTS'

// 用户模块
export const GET_PERSONAL_INFO_LESSONS = 'user/GET_PERSONAL_INFO_LESSONS'
export const GET_PERSONAL_INFO_STUDY = 'user/GET_PERSONAL_INFO_STUDY'
export const GET_PERSONAL_INFO_LIVES = 'user/GET_PERSONAL_INFO_LIVES'
export const GET_PERSONAL_INFO_BASE = 'user/GET_PERSONAL_INFO_BASE'
export const GET_PERSONAL_INFO_JOB_CIRCLES = 'user/GET_PERSONAL_INFO_JOB_CIRCLES'
export const GET_MEMBER_INFOS = 'user/GET_MEMBER_INFOS'
